"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

APP_VERSION="0.0.0"

from setuptools import setup

APP = ['VPFlasher.py']
DATA_FILES = ['ChmodBPF', 'chmodbpf-postinstall.sh', 'com.bashtheshell.ChmodBPF.plist']
OPTIONS = {
    'argv_emulation': False, 
    'iconfile': 'vpflasher_icon.icns',
    'plist': {
        'CFBundleName': 'VPFlasher',
        'CFBundleDisplayName': 'VPFlasher',
        'CFBundleGetInfoString': "Videophone Flasher",
        'CFBundleIdentifier': "com.bashtheshell.macos.vpflasher",
        'CFBundleVersion': APP_VERSION,
        'CFBundleShortVersionString': APP_VERSION,
        'NSHumanReadableCopyright': u"Copyright © 2019, Travis Johnson",
        'CFBundleDevelopmentRegion': 'English'
    }  
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
